// SPDX-License-Identifier: Apache-2.0
import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { createHash } from "node:crypto";

test("attachment metadata survives draft recovery, encryption and vendor file verification", async ({ page, context }, testInfo) => {
  const bytes = Buffer.from("Private attachment example: synthetic evidence only\n");
  const digest = createHash("sha256").update(bytes).digest("hex");
  const file = { name: "private-proof.txt", mimeType: "text/plain", buffer: bytes };
  await page.goto("/");
  await page.getByRole("button", { name: /Seal a vulnerability/ }).click();
  const steps = page.getByLabel("Reproduction steps");
  await steps.fill("First synthetic step");
  await steps.press("End");
  await steps.press("Enter");
  await steps.pressSequentially("Second synthetic step");
  await expect(steps).toHaveValue("First synthetic step\nSecond synthetic step");
  await page.getByLabel("Hash a local attachment").setInputFiles(file);
  await expect(page.getByText(digest, { exact: true })).toBeVisible();
  await page.getByLabel("Hash a local attachment").setInputFiles(file);
  await expect(page.getByRole("alert")).toHaveText("This filename and digest are already attached");
  await page.getByText("Enter an existing digest", { exact: true }).click();
  await page.getByLabel("Attachment filename", { exact: true }).fill("manual-proof.bin");
  await expect(page.getByRole("button", { name: /Encrypt & seal/ })).toBeDisabled();
  await page.getByLabel("Attachment media type", { exact: true }).fill("application/octet-stream");
  await page.getByLabel("Attachment size in bytes", { exact: true }).fill("-1");
  await page.getByLabel("Attachment SHA-256", { exact: true }).fill("00".repeat(32));
  await page.getByRole("button", { name: "Add attachment metadata" }).click();
  await expect(page.getByRole("alert")).toHaveText("Enter a nonnegative whole-byte size");
  await page.getByLabel("Attachment size in bytes", { exact: true }).fill("0");
  await page.getByRole("button", { name: "Add attachment metadata" }).click();
  await expect(page.getByText("2 attachment entry(s)", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Remove manual-proof.bin" }).click();
  await expect(page.getByText("1 attachment entry(s)", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Private recovery" }).click();
  await page.getByLabel("Backup password", { exact: true }).fill("Attachment draft backup password");
  await page.getByLabel("Confirm backup password").fill("Attachment draft backup password");
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download encrypted backup" }).click();
  const backupPath = testInfo.outputPath("attachment-recovery.json");
  await (await downloadPromise).saveAs(backupPath);
  expect(await readFile(backupPath, "utf8")).not.toContain(file.name);
  await page.close();
  const restored = await context.newPage();
  await restored.goto("/");
  await restored.getByRole("button", { name: "Private recovery" }).click();
  await restored.getByLabel("Recovery file").setInputFiles(backupPath);
  await restored.getByLabel("Recovery password", { exact: true }).fill("Attachment draft backup password");
  await restored.getByRole("button", { name: "Restore encrypted backup" }).click();
  await expect(restored.getByText(digest, { exact: true })).toBeVisible();
  await expect(restored.getByLabel("Reproduction steps")).toHaveValue("First synthetic step\nSecond synthetic step");
  await restored.getByRole("checkbox").check();
  const uploadPromise = restored.waitForRequest((request) => request.method() === "PUT" && request.url().includes("/v1/blobs/"));
  await restored.getByRole("button", { name: /Encrypt & seal/ }).click();
  const upload = (await uploadPromise).postData()!;
  expect(upload).not.toContain(file.name);
  expect(upload).not.toContain(digest);
  expect(upload).not.toContain(bytes.toString());
  await restored.getByRole("button", { name: /Continue as vendor/ }).click();
  await expect(restored.getByText(digest, { exact: true })).toBeVisible();
  const check = restored.getByLabel("Check local file against private-proof.txt", { exact: true });
  await check.setInputFiles({ ...file, buffer: Buffer.from("Changed file") });
  await expect(restored.getByText("File does not match the sealed attachment digest and size.", { exact: true })).toBeVisible();
  await check.setInputFiles(file);
  await expect(restored.getByText("File bytes match the sealed attachment digest and size.", { exact: true })).toBeVisible();
  if (process.env.VULNSEAL_CAPTURE_VISUALS === "1") {
    await restored.evaluate(() => { (document.activeElement as HTMLElement)?.blur(); window.scrollTo(0, 0); });
    await restored.screenshot({ path: `docs/screenshots/${testInfo.project.name}-attachments.png`, fullPage: true });
  }
});
