// SPDX-License-Identifier: Apache-2.0
import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { pureCircuits } from "@vulnseal/contract";
import { bytesToHex, hexToBytes } from "@vulnseal/shared";
import { recoveryFixture } from "../web/src/test/recovery-fixture.js";
import { decryptRoleVault, encryptRoleVault, withSubmissionAttempt, withSubmissionNotes, withRetestChoice } from "../web/src/role-recovery.js";

test("saved retest failure remains explicit after offline encrypted recovery", async ({ page }) => {
  const { snapshot } = await recoveryFixture();
  const report = { network: "preprod", contractAddress: "ab".repeat(32), programId: snapshot.programId, reportId: snapshot.report!.id, envelope: snapshot.report!.envelope, key: snapshot.report!.key, salt: snapshot.report!.salt };
  const id = "cd".repeat(32), password = "Saved retest choice password";
  const pending = await withSubmissionAttempt({ version: 1, role: "researcher", network: "preprod", contractAddress: report.contractAddress, programId: report.programId, actorSecret: snapshot.researcherSecret, reports: [report] }, id, { circuit: "submitRetest", reportId: report.reportId });
  const encrypted = await encryptRoleVault(await withRetestChoice(pending, id, false), password);
  await page.goto("/#roles");
  await page.getByLabel("Restore backups without connecting Lace").check();
  await page.getByLabel("Single-role backup file").setInputFiles({ name: "retest.json", mimeType: "application/json", buffer: Buffer.from(encrypted) });
  await page.getByLabel("Role restore password").fill(password);
  await page.getByRole("button", { name: "Restore role workspace" }).click();
  await page.getByRole("button", { name: "Save role backup" }).click();
  await expect(page.getByText(/Saved retest choice: Fail/)).toBeVisible();
  await expect(page.getByText(/Saved retest choice: Pass/)).toHaveCount(0);
  await expect(page.getByText(/local intent, not a verified outcome/)).toBeVisible();
});

test("private notes stay with their reports across offline switching and encrypted recovery", async ({ page, context }, testInfo) => {
  const { snapshot, sealed } = await recoveryFixture();
  const password = "Preserve two private report notes";
  const first = { network: "preprod", contractAddress: "ab".repeat(32), programId: snapshot.programId, reportId: snapshot.report!.id, envelope: snapshot.report!.envelope, key: snapshot.report!.key, salt: snapshot.report!.salt };
  const secondSalt = "67".repeat(32);
  const second = { ...first, salt: secondSalt, reportId: bytesToHex(pureCircuits.deriveReportCommitment(hexToBytes(first.programId), Uint8Array.from(sealed.canonicalReportDigest), hexToBytes(secondSalt))) };
  const transactionId = "cd".repeat(32);
  const historical = { reportId: first.reportId, text: "Private context from the original attempt", tier: "2" };
  const attempted = await withSubmissionAttempt({ version: 1, role: "vendor", network: "preprod", contractAddress: first.contractAddress, programId: first.programId, actorSecret: snapshot.vendorSecret, reports: [first, second] }, transactionId, { circuit: "beginTriage", reportId: first.reportId });
  const initial = await encryptRoleVault(await withSubmissionNotes(attempted, transactionId, historical), password);
  await page.goto("/#roles");
  await page.getByLabel("Restore backups without connecting Lace").check();
  await page.getByLabel("Single-role backup file").setInputFiles({ name: "two-reports.json", mimeType: "application/json", buffer: Buffer.from(initial) });
  await page.getByLabel("Role restore password").fill(password);
  await page.getByRole("button", { name: "Restore role workspace" }).click();
  await expect(page.getByRole("heading", { name: "Program reports" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Refresh ledger" })).toHaveCount(0);
  await page.getByText("Read selected private report").click();
  await expect(page.getByRole("heading", { name: "Private vulnerability" })).toBeVisible();
  await expect(page.getByRole("option", { name: /Private vulnerability/ })).toHaveCount(2);
  await page.getByLabel("Find saved reports").fill(second.reportId);
  await expect(page.getByText(/1 of 2 reports match/)).toBeVisible();
  await expect(page.getByLabel("Workspace report")).toHaveValue(first.reportId);
  await page.getByLabel("Workspace report").selectOption(second.reportId);
  await page.getByLabel("Find saved reports").fill("");
  await page.getByLabel("Workspace report").selectOption(first.reportId);
  await page.getByLabel("Browser copy password", { exact: true }).fill(password);
  await page.getByLabel("Confirm browser copy password").fill(password);
  await page.getByRole("button", { name: "Enable encrypted browser autosave" }).click();
  await expect(page.getByText(/Saved encrypted browser copy/)).toBeVisible();
  const firstText = "  Private triage rationale\n\nUnfinished release reference  ";
  const secondText = "Different report, different private notes";
  const notes = page.getByLabel("Private decision, patch reference or retest notes");
  await notes.fill(firstText);
  await page.getByLabel("Public severity / reward tier").selectOption("4");
  await page.getByLabel("Workspace report").selectOption(second.reportId);
  await expect(notes).toHaveValue("");
  await expect(page.getByLabel("Public severity / reward tier")).toHaveValue("3");
  await notes.fill(secondText);
  await page.getByLabel("Public severity / reward tier").selectOption("1");
  await page.getByLabel("Workspace report").selectOption(first.reportId);
  await expect(notes).toHaveValue(firstText);
  await expect(page.getByLabel("Public severity / reward tier")).toHaveValue("4");
  await expect(page.getByText(/Draft edits, report notes, prepared reports and received disclosures are held in memory/)).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Begin triage" })).toHaveCount(0);
  await page.getByRole("button", { name: "Save role backup" }).click();
  await page.getByLabel("Role backup password", { exact: true }).fill(password);
  await page.getByLabel("Confirm role backup password").fill(password);
  const downloaded = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download single-role backup" }).click();
  const path = testInfo.outputPath("report-notes.json");
  await (await downloaded).saveAs(path);
  const encrypted = await readFile(path, "utf8");
  expect(encrypted).not.toContain(firstText);
  const recovered = await decryptRoleVault(encrypted, password);
  expect(recovered.version).toBe(8);
  expect(recovered.submissionAttempts![0]!.notes).toEqual(historical);
  expect(recovered.reportNotes).toEqual([{ reportId: first.reportId, text: firstText, tier: "4" }, { reportId: second.reportId, text: secondText, tier: "1" }]);
  await page.close();
  const fresh = await context.newPage();
  await fresh.goto("/#roles");
  await fresh.getByLabel("Restore backups without connecting Lace").check();
  await fresh.getByLabel("Saved browser workspace").selectOption({ index: 1 });
  await fresh.getByLabel("Browser unlock password").fill(password);
  await fresh.getByRole("button", { name: "Unlock browser workspace" }).click();
  await expect(fresh.getByLabel("Private decision, patch reference or retest notes")).toHaveValue(firstText);
  await fresh.getByLabel("Workspace report").selectOption(second.reportId);
  await expect(fresh.getByLabel("Private decision, patch reference or retest notes")).toHaveValue(secondText);
  await fresh.getByText("Private notes saved with this attempt").click();
  await expect(fresh.getByText(historical.text, { exact: true })).toBeVisible();
  const inspector = await context.newPage();
  await inspector.goto("/#roles");
  await inspector.getByLabel("Journal backup file").setInputFiles({ name: "history.json", mimeType: "application/json", buffer: Buffer.from(encrypted) });
  await inspector.getByLabel("Journal backup password").fill(password);
  await inspector.getByRole("button", { name: "Read recovery journal" }).click();
  await expect(inspector.getByText(new RegExp(transactionId))).toBeVisible();
  await expect(inspector.getByText(historical.text, { exact: true })).toHaveCount(0);
  await expect(inspector.getByText("Private notes saved with this attempt")).toHaveCount(0);
  await expect(fresh.getByLabel("Public severity / reward tier")).toHaveValue("1");
});
