// SPDX-License-Identifier: Apache-2.0
import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { decryptRoleVault } from "../web/src/role-recovery.js";

test("unfinished vendor program survives encrypted autosave, tab changes and file recovery", async ({ page, context }, testInfo) => {
  const writes: string[] = [];
  context.on("request", (request) => { if (["POST", "PUT"].includes(request.method())) writes.push(request.url()); });
  const password = "Retain my unfinished vendor policy";
  await page.goto("/#roles");
  await page.getByRole("button", { name: "Prepare vendor identity" }).click();
  await page.getByLabel("Browser copy password", { exact: true }).fill(password);
  await page.getByLabel("Confirm browser copy password").fill(password);
  await page.getByRole("button", { name: "Enable encrypted browser autosave" }).click();
  await expect(page.getByText(/Saved encrypted browser copy/)).toBeVisible();
  await page.getByRole("button", { name: "Reports", exact: true }).click();
  const name = "  Unfinished private vendor program  ", rewards = "Critical reward\n\n  unfinished details  \n";
  await page.getByLabel("Program name", { exact: true }).fill(name);
  await page.getByLabel("Primary scope", { exact: true }).fill("");
  await page.getByRole("textbox", { name: "Reward policy", exact: true }).fill(rewards);
  await page.getByRole("combobox", { name: "Response days", exact: true }).selectOption("14");
  await page.getByRole("combobox", { name: "Disclosure days", exact: true }).selectOption("60");
  await expect(page.getByText(/Draft edits, report notes, prepared reports and received disclosures are held in memory/)).toHaveCount(0);
  await page.getByRole("button", { name: "Save role backup", exact: true }).click();
  await page.getByRole("button", { name: "Reports", exact: true }).click();
  await expect(page.getByLabel("Program name", { exact: true })).toHaveValue(name);
  await expect(page.getByRole("textbox", { name: "Reward policy", exact: true })).toHaveValue(rewards);
  const rows = await page.evaluate(async () => {
    const db = await new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open("vulnseal-encrypted-roles", 1); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
    try { return await new Promise<{ id: string; encrypted: string }[]>((resolve, reject) => { const request = db.transaction("roles", "readonly").objectStore("roles").getAll(); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); } finally { db.close(); }
  });
  expect(rows).toHaveLength(1);
  expect(JSON.stringify(rows)).not.toContain(name.trim());
  const saved = await decryptRoleVault(rows[0]!.encrypted, password);
  expect(saved.version).toBe(11);
  expect(saved.programDraft).toMatchObject({ name, primaryScope: "", rewardPolicy: rewards, responseDays: "14", disclosureDays: "60" });
  await page.getByRole("button", { name: "Save role backup", exact: true }).click();
  await page.getByLabel("Role backup password", { exact: true }).fill(password);
  await page.getByLabel("Confirm role backup password").fill(password);
  const downloaded = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download single-role backup" }).click();
  const filename = testInfo.outputPath("vendor-program-draft.json");
  await (await downloaded).saveAs(filename);
  expect(await decryptRoleVault(await readFile(filename, "utf8"), password)).toEqual(saved);
  await page.close();
  const fresh = await context.newPage();
  await fresh.goto("/#roles");
  await fresh.getByLabel("Restore backups without connecting Lace").check();
  await fresh.getByLabel("Saved browser workspace").selectOption(rows[0]!.id);
  await fresh.getByLabel("Browser unlock password").fill(password);
  await fresh.getByRole("button", { name: "Unlock browser workspace" }).click();
  await expect(fresh.getByRole("heading", { name: "Vendor workspace" })).toBeVisible();
  await fresh.getByRole("button", { name: "Reports", exact: true }).click();
  await expect(fresh.getByLabel("Program name", { exact: true })).toHaveValue(name);
  await expect(fresh.getByLabel("Primary scope", { exact: true })).toHaveValue("");
  await expect(fresh.getByRole("textbox", { name: "Reward policy", exact: true })).toHaveValue(rewards);
  await expect(fresh.getByRole("combobox", { name: "Response days", exact: true })).toHaveValue("14");
  await expect(fresh.getByRole("combobox", { name: "Disclosure days", exact: true })).toHaveValue("60");
  await fresh.close();
  const fromFile = await context.newPage();
  await fromFile.goto("/#roles");
  await fromFile.getByLabel("Restore backups without connecting Lace").check();
  await fromFile.getByLabel("Single-role backup file").setInputFiles(filename);
  await fromFile.getByLabel("Role restore password").fill(password);
  await fromFile.getByRole("button", { name: "Restore role workspace" }).click();
  await expect(fromFile.getByRole("heading", { name: "Vendor workspace" })).toBeVisible();
  await fromFile.getByRole("button", { name: "Reports", exact: true }).click();
  await expect(fromFile.getByLabel("Program name", { exact: true })).toHaveValue(name);
  await expect(fromFile.getByLabel("Primary scope", { exact: true })).toHaveValue("");
  await expect(fromFile.getByRole("textbox", { name: "Reward policy", exact: true })).toHaveValue(rewards);
  await expect(fromFile.getByRole("combobox", { name: "Response days", exact: true })).toHaveValue("14");
  await expect(fromFile.getByRole("combobox", { name: "Disclosure days", exact: true })).toHaveValue("60");
  expect(writes).toEqual([]);
});
