// SPDX-License-Identifier: Apache-2.0
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { hexToBytes } from "@vulnseal/shared";
import { pureCircuits } from "@vulnseal/contract";
import { recoveryFixture } from "./test/recovery-fixture.js";
import { defaultProgramDraft, programConstructor } from "./program.js";
import { encryptRecovery } from "./recovery.js";
import { submissionReceipt } from "./submission-receipt.js";
const mocks = vi.hoisted(() => ({ connect: vi.fn(), join: vi.fn(), write: vi.fn() }));
vi.mock("./midnight/browser-providers.js", () => ({ initializeBrowserProviders: mocks.connect }));
vi.mock("@vulnseal/api/api", () => ({ VulnSealApi: { join: mocks.join } }));
vi.mock("./recovery-storage.js", async original => ({ ...await original<typeof import("./recovery-storage.js")>(), writeStoredRecovery: mocks.write }));
import App from "./App.js";
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
it("blocks a full confirmed journal before creating new submission uncertainty", async () => {
  const { snapshot: source, sealed } = await recoveryFixture();
  const reportAttempts = Array.from({ length: 1000 }, (_, index) => ({ circuit: "beginTriage" as const, reportId: (index + 1).toString(16).padStart(64, "0"), transactionId: (index + 1).toString(16).padStart(64, "0"), startedAt: "2026-09-11T00:00:00.000Z", outcome: "sdk-confirmed" as const, request: { nextStatus: "TRIAGED" as const, severity: 3, rationale: "Old decision", patchReference: "", retestNotes: "" } }));
  const snapshot = { ...source, version: 8 as const, mode: "midnight" as const, network: "preprod", contractAddress: "ab".repeat(32), programDraft: defaultProgramDraft, pendingReport: null, uncertainTransition: null, attachmentDraft: null, reportAttempts };
  const programId = hexToBytes(source.programId), reportId = hexToBytes(source.report!.id);
  const researcherKey = pureCircuits.deriveResearcherKey(programId, reportId, hexToBytes(source.researcherSecret));
  const record = { commitment: reportId, ciphertextDigest: sealed.ciphertextDigest, researcherKey, submissionReceipt: submissionReceipt(reportId, sealed.ciphertextDigest, researcherKey), status: 0, severity: 0n, patchCommitment: new Uint8Array(32), retestCommitment: new Uint8Array(32), payoutReceipt: new Uint8Array(32) };
  const ledger = { ...await programConstructor(programId, source.policy), ownerKey: pureCircuits.deriveVendorKey(programId, hexToBytes(source.vendorSecret)), reports: { member: () => true, lookup: () => record } };
  const api = { contractAddress: snapshot.contractAddress, readPublicState: vi.fn().mockResolvedValue({ ledger }), usePrivateState: vi.fn(), beginTriage: vi.fn() };
  mocks.connect.mockResolvedValue({}); mocks.join.mockResolvedValue(api);
  mocks.write.mockImplementation(async (id, label, encrypted) => ({ id, label, encrypted, revision: 1, updatedAt: new Date().toISOString() }));
  const fetch = vi.fn().mockResolvedValue(new Response(sealed.serializedEnvelope)); vi.stubGlobal("fetch", fetch);
  const password = "Synthetic full journal password", serialized = await encryptRecovery(snapshot, password);
  render(<App />); fireEvent.click(screen.getByRole("button", { name: "Private recovery" }));
  const file = new File([serialized], "full-journal.json"); Object.defineProperty(file, "text", { value: async () => serialized });
  fireEvent.change(screen.getByLabelText("Recovery file"), { target: { files: [file] } });
  fireEvent.change(screen.getByLabelText("Recovery password"), { target: { value: password } });
  fireEvent.submit(screen.getByRole("button", { name: "Restore encrypted backup" }).closest("form")!);
  await screen.findByText(/Recovered report.*ledger checked/, {}, { timeout: 5000 });
  fireEvent.click(screen.getByRole("button", { name: "Private recovery" }));
  fireEvent.change(screen.getByLabelText("Autosave password"), { target: { value: password } });
  fireEvent.change(screen.getByLabelText("Confirm autosave password"), { target: { value: password } });
  fireEvent.submit(screen.getByRole("button", { name: "Enable encrypted autosave" }).closest("form")!);
  await screen.findByRole("button", { name: "Stop encrypted autosave" }, { timeout: 5000 });
  fireEvent.click(screen.getByRole("button", { name: "Submission receipt" }));
  fireEvent.click(screen.getByRole("button", { name: /Continue as vendor/ }));
  fireEvent.click(await screen.findByRole("button", { name: "Begin authorized triage" }));
  await screen.findAllByText(/Report journal reached its 1,000-entry limit/);
  expect(screen.queryByText("Transaction outcome unknown: beginTriage")).not.toBeInTheDocument();
  expect(api.usePrivateState).not.toHaveBeenCalled(); expect(api.beginTriage).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole("button", { name: "Private recovery" }));
  expect(screen.getByRole("button", { name: "Stop encrypted autosave" })).toBeEnabled();
  fireEvent.click(screen.getByRole("button", { name: "Submission receipt" }));
  expect(screen.getByRole("button", { name: "Seal another" })).toBeEnabled();
  fireEvent.click(screen.getByRole("button", { name: "Seal another" }));
  fireEvent.click(screen.getByRole("checkbox")); fireEvent.click(screen.getByRole("button", { name: /Encrypt & seal/ }));
  await waitFor(() => expect(screen.getAllByText(/Report journal reached its 1,000-entry limit/).length).toBeGreaterThan(0));
  expect(fetch.mock.calls.some(([, init]) => init?.method === "PUT")).toBe(false);
  expect(screen.queryByText(/Its outcome needs reconciliation/)).not.toBeInTheDocument();
}, 15_000);
