// SPDX-License-Identifier: Apache-2.0
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, expect, it, vi } from "vitest";
import { decryptRoleVault, encryptRoleVault } from "./role-recovery.js";
import { recoveryFixture } from "./test/recovery-fixture.js";
import type { StoredRole } from "./role-storage.js";
const mocks = vi.hoisted(() => ({ join: vi.fn(), list: vi.fn(), read: vi.fn(), write: vi.fn() }));
vi.mock("./role-network.js", () => ({ joinRoleVault: mocks.join }));
vi.mock("./role-storage.js", () => ({ listStoredRoles: mocks.list, readStoredRole: mocks.read, writeStoredRole: mocks.write, deleteStoredRole: vi.fn() }));
import { RoleWorkspace } from "./RoleWorkspace.js";
afterEach(() => { cleanup(); vi.clearAllMocks(); });

it("blocks unjournaled submission, saves before an uncertain result, and restores the attempt", async () => {
  const { snapshot } = await recoveryFixture();
  const vault = { version: 1 as const, role: "vendor" as const, network: "preprod", contractAddress: "ab".repeat(32), programId: snapshot.programId, actorSecret: snapshot.vendorSecret, reports: [{ network: "preprod", contractAddress: "ab".repeat(32), programId: snapshot.programId, reportId: snapshot.report!.id, envelope: snapshot.report!.envelope, key: snapshot.report!.key, salt: snapshot.report!.salt }] };
  const password = "Journal workspace password", txId = "00315eaad1b87f436849790da0f0072be407dfdf9079b78f15e73c838b9ede2c19";
  let row: StoredRole | undefined, checkpoint: (id: string) => Promise<void>;
  mocks.list.mockImplementation(async () => row ? [{ id: row.id, label: row.label, revision: row.revision, updatedAt: row.updatedAt }] : []);
  mocks.read.mockImplementation(async () => row);
  mocks.write.mockImplementation(async (id, label, encrypted, revision) => { row = { id, label, encrypted, revision: (revision ?? 0) + 1, updatedAt: new Date().toISOString() }; return row; });
  const broadcast = vi.fn();
  const state = { ledger: { reports: { member: () => true, lookup: () => ({ status: 0 }) } } };
  const session = { readPublicState: vi.fn().mockResolvedValue(state), execute: vi.fn(async () => {
    await checkpoint(txId);
    expect((await decryptRoleVault(row!.encrypted, password)).submissionAttempts?.[0]?.transactionId).toBe(txId);
    broadcast(); throw new Error("Finality response lost after submission");
  }) };
  mocks.join.mockImplementation(async (_vault, beforeSubmit) => { checkpoint = beforeSubmit; return { session, snapshot: state }; });
  const serialized = await encryptRoleVault(vault, password);
  const file = new File([serialized], "role.json", { type: "application/json" });
  Object.defineProperty(file, "text", { value: async () => serialized });
  const user = userEvent.setup(); const view = render(<RoleWorkspace />);
  await user.upload(screen.getByLabelText("Single-role backup file"), file);
  await user.type(screen.getByLabelText("Role restore password"), password);
  fireEvent.submit(screen.getByRole("button", { name: "Restore role workspace" }).closest("form")!);
  await screen.findByRole("heading", { name: "Vendor workspace" });
  await user.click(screen.getByRole("button", { name: "Begin triage" }));
  await screen.findByText(/Enable encrypted browser autosave before submitting/);
  expect(broadcast).not.toHaveBeenCalled();
  await user.click(screen.getByRole("button", { name: "Refresh ledger" }));
  await user.type(screen.getByLabelText("Browser copy password"), password);
  await user.type(screen.getByLabelText("Confirm browser copy password"), password);
  await user.click(screen.getByRole("button", { name: "Enable encrypted browser autosave" }));
  await screen.findByText(/Saved encrypted browser copy/);
  mocks.write.mockRejectedValueOnce(new Error("Journal storage unavailable"));
  await user.click(screen.getByRole("button", { name: "Begin triage" }));
  await screen.findByRole("alert");
  expect(broadcast).not.toHaveBeenCalled();
  expect((await decryptRoleVault(row!.encrypted, password)).submissionAttempts).toBeUndefined();
  await user.click(screen.getByRole("button", { name: "Refresh ledger" }));
  await user.type(screen.getByLabelText("Browser copy password"), password);
  await user.type(screen.getByLabelText("Confirm browser copy password"), password);
  await user.click(screen.getByRole("button", { name: "Enable encrypted browser autosave" }));
  await screen.findByRole("button", { name: "Stop browser autosave" });
  await user.click(screen.getByRole("button", { name: "Begin triage" }));
  await screen.findByText("Finality response lost after submission");
  expect(broadcast).toHaveBeenCalledOnce();
  expect(row!.encrypted).not.toContain(txId);
  await screen.findByText(new RegExp(txId));
  view.unmount(); render(<RoleWorkspace />);
  await user.selectOptions(await screen.findByLabelText("Saved browser workspace"), row!.id);
  await user.type(screen.getByLabelText("Browser unlock password"), password);
  await user.click(screen.getByRole("button", { name: "Unlock browser workspace" }));
  await screen.findByRole("heading", { name: "Vendor workspace" });
  await screen.findByText(new RegExp(txId));
  expect(broadcast).toHaveBeenCalledOnce();
}, 30_000);
